### ISSUE TITLE
Crash when using the interface within player inventory after clicking the furnace icon

### ISSUE THREAD

**Issue by Brin1771** [AlphaMode/PortableTables#2]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 11/10/22, 8:57 AM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "net.fabricmc.fabric.api.registry.FuelRegistry.get(net.minecraft.class_1935)" is null
	at me.alphamode.portablecrafting.tables.furnace.PortableFurnace.getFuelTime(PortableFurnace.java:52)
	at me.alphamode.portablecrafting.tables.furnace.PortableFurnace.method_7888(PortableFurnace.java:72)
	at net.minecraft.class_1799.method_7917(class_1799.java:528)
	at net.minecraft.class_1661.method_7381(class_1661.java:256)
	at net.minecraft.class_1657.method_6007(class_1657.java:557)
	at net.minecraft.class_746.method_6007(class_746.java:836)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1657.method_5773(class_1657.java:275)
	at net.minecraft.class_746.method_5773(class_746.java:212)
	at net.minecraft.class_638.method_18646(class_638.java:217)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)
	at net.minecraft.class_310.method_1574(class_310.java:1761)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.alphamode.portablecrafting.tables.furnace.PortableFurnace.getFuelTime(PortableFurnace.java:52)
	at me.alphamode.portablecrafting.tables.furnace.PortableFurnace.method_7888(PortableFurnace.java:72)
	at net.minecraft.class_1799.method_7917(class_1799.java:528)
	at net.minecraft.class_1661.method_7381(class_1661.java:256)
	at net.minecraft.class_1657.method_6007(class_1657.java:557)
	at net.minecraft.class_746.method_6007(class_746.java:836)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1657.method_5773(class_1657.java:275)
	at net.minecraft.class_746.method_5773(class_746.java:212)
	at net.minecraft.class_638.method_18646(class_638.java:217)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 255
	Entity Name: Brin1771
	Entity's Exact location: 1208.35, 63.00, 2303.88
	Entity's Block location: World: (1208,63,2303), Section: (at 8,15,15 in 75,3,143; chunk contains blocks 1200,-64,2288 to 1215,319,2303), Region: (2,4; contains chunks 64,128 to 95,159, blocks 1024,-64,2048 to 1535,319,2559)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)
	at net.minecraft.class_310.method_1574(class_310.java:1761)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['Brin1771'/255, l='ClientLevel', x=1208.35, y=63.00, z=2303.88]]
	Chunk stats: 961, 614
	Level dimension: minecraft:overworld
	Level spawn location: World: (1217,63,2288), Section: (at 1,15,0 in 76,3,143; chunk contains blocks 1216,-64,2288 to 1231,319,2303), Region: (2,4; contains chunks 64,128 to 95,159, blocks 1024,-64,2048 to 1535,319,2559)
	Level time: 775441 game time, 154970 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2848808888 bytes (2716 MiB) / 6681526272 bytes (6372 MiB) up to 8522825728 bytes (8128 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX550/550 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x699f
	Graphics card #0 versionInfo: DriverVersion=30.0.15021.1001
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 31143.58
	Virtual memory used (MB): 18996.65
	Swap memory total (MB): 14848.00
	Swap memory used (MB): 167.75
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8128m
	Fabric Mods: 
		arcanus: Arcanus 1.29
		artifacts: Artifacts 7.0.3+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		automobility: Automobility 0.2.1+1.18.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
			jsonem: JsonEM 0.1.2
			myron: Myron 1.6.3+1.18.1
		balm-fabric: Balm 3.2.0+0
		botania: Botania 1.18.2-435-FABRIC
			fiber: fiber 0.23.0-2
			reach-entity-attributes: Reach Entity Attributes 2.1.1
		chestcavity: Chest Cavity 2.16.2
			modify-drops-api: Modify Drops API 0.4.0.2
		cloth-config: Cloth Config v6 6.4.90
			cloth-basic-math: cloth-basic-math 0.6.1
		cookingforblockheads: Cooking for Blockheads 12.1.1
		copper_pipe: Simple Copper Pipes 1.11.3-1.18.2
		customizableelytra: Customizable Elytra 1.5.3-1.18
		easybreeding: EasyBreeding 7.0.0
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		fabric-api: Fabric API 0.59.1+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.6+651bcc5960
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.23+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.1+c85f2e3860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.2+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.20+489d6f8260
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.19+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.2+17cbbd4360
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.14+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+1997ad1260
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.2+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.4+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.23+2d30af4b60
			fabric-networking-v0: Fabric Networking (v0) 0.3.10+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.3+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.11+bb2e047760
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.14+5d58937860
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.4+41a02c8a60
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.2+446e059560
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.2+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.5+kotlin.1.7.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.4
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.10
		healthbarplus: Health Bar Plus 1.0.0
		icarus: Icarus 1.11
		java: Java HotSpot(TM) 64-Bit Server VM 17
		jei: Just Enough Items 10.2.1.278
		journeymap-fabric: Journeymap 5.9.0beta2
			journeymap-api-fabric: JourneyMap API 1.18.2-1.9-fabric-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		mcwdoors: Macaw's Doors 1.0.7
		minecraft: Minecraft 1.18.2
		miningutility: Mining Utility 1.2.3+1.18
		mousetweaks: Mouse Tweaks 2.22
		onastick: On A Stick 2.0.0
		owo: oωo 0.7.2-no-cme+1.18
		patchouli: Patchouli 1.18.2-71.1-FABRIC
		pfm: Paladin's Furniture 1.1.1
		pickablevillagers: Pickable Villagers 1.2.4+1.18.2
		plantinajar: Plant In A Jar 2.3.1
			libgui: LibGui 5.4.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
			org_objenesis_objenesis: objenesis 3.2
		portable_tables: Portable Tables 1.3
		ringofrepair: Ring of Repair 1.4.3
		scout: Scout 1.1.1
		simple_cobblestone_generator: Simple cobblestone generator 1.1.8
		simplegrinder: Simple Grinder 18_2.0.2
		the_extractinator: The Extractinator 1.0.8
		toms_storage: Tom's Simple Storage Mod 1.4.3
		travelersbackpack: Traveler's Backpack 1.18.2-7.1.10
		trinkets: Trinkets 3.3.1
		twilightforest: The Twilight Forest 4.1.268
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
			com_electronwill_night-config_core: core 3.6.3
			com_electronwill_night-config_toml: toml 3.6.3
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forge_tags: Forge Tags 2.1
			forgeconfigapiport: Forge Config API Port 3.2.0
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 1.1.342-beta+1.18.2-dev.dd61cdc
				com_github_llamalad7_mixinextras: MixinExtras 0.0.10
				serialization_hooks: Serialization Hooks 0.2.0+1.18.f5d4aa6
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX550/550 Series GL version 3.2.14800 Core Profile Forward-Compatible Context 22.4.1 30.0.15021.1001, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Brin1771'/255, l='ServerLevel[W2n]', x=1208.35, y=63.00, z=2303.88]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable

**Comment by AlphaMode** [comment]
This should have been fixed in 2.0, I'll see about backporting it to 1.18.2 later today

**Comment by AlphaMode** [comment]
Fixed in 2.1+1.18.2
